//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace byte4bite_hackathon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PantryCoordinator
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int FoodPantryID { get; set; }
        public bool IsAdministrator { get; set; }
    
        public virtual FoodPantry FoodPantry { get; set; }
    }
}
