//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace byte4bite_hackathon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedItem
    {
        public int ID { get; set; }
        public int FoodPantryID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> FulfillByDate { get; set; }
    
        public virtual FoodPantry FoodPantry { get; set; }
        public virtual Item Item { get; set; }
    }
}
